# Generated by Django 3.2.7 on 2021-09-26 21:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the category', max_length=50)),
                ('is_active', models.BooleanField(help_text='Is this category still in use? (Affects if it appears in the new Clothes form)')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the color', max_length=20)),
                ('is_active', models.BooleanField(help_text='Is this color still in use? (Affects if it appears in the new Clothes form)')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the condition', max_length=50)),
                ('is_active', models.BooleanField(help_text='Is this condition still in use? (Affects if it appears in the new Clothes form)')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250)),
                ('date_imported', models.DateField(default=datetime.date.today, help_text='Date the file was imported')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the gender', max_length=20)),
                ('is_active', models.BooleanField(help_text='Is this gender still in use? (Affects if it appears in the new Clothes form)')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the size', max_length=30)),
                ('is_active', models.BooleanField(help_text='Is this size size in use? (Affects if it appears in the new Clothes form)')),
                ('category', models.ForeignKey(help_text='Category that size relates to', on_delete=django.db.models.deletion.CASCADE, to='pantry.category')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(blank=True, help_text='Item number for record purposes', null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('brand', models.CharField(blank=True, help_text='Brand of clothing, if available', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of clothing', max_length=500, null=True)),
                ('inventory_date', models.DateField(default=datetime.date.today, help_text='Date the item of clothing was added to the pantry')),
                ('is_checked_out', models.BooleanField(default=False, help_text='Has the user checked out with these items?')),
                ('date_checked_out', models.DateField(blank=True, help_text='Date the item of clothing was checked out', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.category')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.color')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.condition')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.file')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.gender')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.size')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
