# Generated by Django 3.2.7 on 2021-09-27 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='is_checked_out',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='item_number',
        ),
    ]
