# Generated by Django 3.2.8 on 2021-10-13 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='last_refill_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
