# Generated by Django 3.2.8 on 2021-10-13 12:35

from django.db import migrations, models

def add_user_wallet(apps, schema_editor):
    Wallet = apps.get_model("pantry", "Wallet")
    User = apps.get_model("auth", "User")

    for user in User.objects.all():
        Wallet.objects.create(user=user, currency=300)

class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_auto_20211013_1212'),
    ]

    operations = [
        migrations.RunPython(add_user_wallet),
    ]
