# Generated by Django 3.2.8 on 2021-11-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0007_clothes_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='date_added_to_cart',
            field=models.DateField(blank=True, help_text='Date the item of clothing was added to users cart', null=True),
        ),
    ]
